package view.menus;

public class AttributeSelection {

}

/*

ATTRIBUT SOUS LA FORME DE PETITS BONUS 

-BONUS DE PV
-GAGNE PLUS D'XP
-BONUS DE DEGATS

-REDUCTION DE LA DUREE DES EFFETS (PARALYSIE, POISON...)
-1 BOMBE SUPPLÉMENTAIRE AU DÉBUT DE PARTIE
-DEVIENT INVISIBLE PENDANT X SECONDES LORSQUE TOUCHÉ PAR UNE BOMBE
-SE SOIGNE D'UN % DES DEGATS INFLIGÉS AUX JOUEURS


*/